call add_topping_to_pizza('4 formaggi','Mozzarella');
call add_topping_to_pizza('4 formaggi','Gorgonzola');
call add_topping_to_pizza('4 formaggi','Toma');
call add_topping_to_pizza('4 formaggi','Fontal');
call add_prices_to_pizza('4 formaggi', 5.50, 7, 13);
call add_topping_to_pizza('4 stagioni','Pomodoro');
call add_topping_to_pizza('4 stagioni','Mozzarella');
call add_topping_to_pizza('4 stagioni','Funghi');
call add_topping_to_pizza('4 stagioni','Carciofini');
call add_topping_to_pizza('4 stagioni','Olive');
call add_topping_to_pizza('4 stagioni','Prosciutto cotto');
call add_prices_to_pizza('4 stagioni', 5.50, 7, 13);
call add_topping_to_pizza('Alex','Noci');
call add_topping_to_pizza('Alex','Prosciutto cotto');
call add_topping_to_pizza('Alex','Mozzarella di bufala');
call add_prices_to_pizza('Alex', 5.50, 7, 13);
call add_topping_to_pizza('Alfa','Mozzarella');
call add_topping_to_pizza('Alfa','Salsiccia');
call add_topping_to_pizza('Alfa','Friarielli');
call add_topping_to_pizza('Alfa','Guanciale');
call add_topping_to_pizza('Alfa','Olive taggiasche');
call add_topping_to_pizza('Alfa','Cipolle');
call add_prices_to_pizza('Alfa', 8.50, 10, 19);
call add_topping_to_pizza('Amatriciana','Pomodoro');
call add_topping_to_pizza('Amatriciana','Mozzarella');
call add_topping_to_pizza('Amatriciana','Guanciale');
call add_topping_to_pizza('Amatriciana','Cipolle');
call add_topping_to_pizza('Amatriciana','Pecorino');
call add_prices_to_pizza('Amatriciana', 5.50, 7, 13);
call add_topping_to_pizza('Andrea','Mozzarella');
call add_topping_to_pizza('Andrea','Ricotta');
call add_topping_to_pizza('Andrea','Prosciutto cotto');
call add_topping_to_pizza('Andrea','Rucola');
call add_prices_to_pizza('Andrea', 5.50, 7, 13);
call add_topping_to_pizza('Appetitosa','Mozzarella');
call add_topping_to_pizza('Appetitosa','Pomodorini');
call add_topping_to_pizza('Appetitosa','Scamorza affumicata');
call add_topping_to_pizza('Appetitosa','Salame piccante');
call add_topping_to_pizza('Appetitosa','Olive nere');
call add_prices_to_pizza('Appetitosa', 6.50, 8, 15);
call add_topping_to_pizza('Atomica','Pomodoro');
call add_topping_to_pizza('Atomica','Mozzarella');
call add_topping_to_pizza('Atomica','Tomini piccanti');
call add_topping_to_pizza('Atomica','Olive verdi piccanti');
call add_prices_to_pizza('Atomica', 5.50, 7, 13);
call add_topping_to_pizza('Bella napoli','Pomodoro');
call add_topping_to_pizza('Bella napoli','Mozzarella fior di latte');
call add_topping_to_pizza('Bella napoli','Basilico fresco');
call add_prices_to_pizza('Bella napoli', 4.50, 6, 11);
call add_topping_to_pizza('Benny','Pomodoro');
call add_topping_to_pizza('Benny','Mozzarella');
call add_topping_to_pizza('Benny','Prosciutto crudo');
call add_topping_to_pizza('Benny','Gorgonzola');
call add_prices_to_pizza('Benny', 5.50, 7, 13);
call add_topping_to_pizza('Beppe','Pomodoro');
call add_topping_to_pizza('Beppe','Mozzarella');
call add_topping_to_pizza('Beppe','Philadelphia');
call add_topping_to_pizza('Beppe','Patatine');
call add_prices_to_pizza('Beppe', 5, 6.50, 12);
call add_topping_to_pizza('Biancaneve','Mozzarella');
call add_topping_to_pizza('Biancaneve','Prosciutto cotto');
call add_prices_to_pizza('Biancaneve', 4.50, 6, 11);
call add_topping_to_pizza('Bismark','Pomodoro');
call add_topping_to_pizza('Bismark','mozzarella');
call add_topping_to_pizza('Bismark','Prosciutto cotto');
call add_topping_to_pizza('Bismark','Uovo');
call add_prices_to_pizza('Bismark', 5.50, 7, 13);
call add_topping_to_pizza('Bomba','Pomodoro');
call add_topping_to_pizza('Bomba','Mozzarella');
call add_topping_to_pizza('Bomba','Peperoni');
call add_topping_to_pizza('Bomba','Salame piccante');
call add_topping_to_pizza('Bomba','Olive nere');
call add_prices_to_pizza('Bomba', 5.50, 7, 13);
call add_topping_to_pizza('Bontà','Pomodoro');
call add_topping_to_pizza('Bontà','Mozzarella');
call add_topping_to_pizza('Bontà','Olive verdi piccanti');
call add_topping_to_pizza('Bontà','Patatine');
call add_topping_to_pizza('Bontà','Salame piccante');
call add_prices_to_pizza('Bontà', 5.50, 7, 13);
call add_topping_to_pizza('Boscaiola','Mozzarella');
call add_topping_to_pizza('Boscaiola','Funghi');
call add_topping_to_pizza('Boscaiola','Salsiccia');
call add_topping_to_pizza('Boscaiola','Prosciutto cotto');
call add_prices_to_pizza('Boscaiola', 6, 7.50, 14);
call add_topping_to_pizza('Bufala','Pomodoro');
call add_topping_to_pizza('Bufala','Mozzarella di bufala');
call add_prices_to_pizza('Bufala', 4.50, 6, 11);
call add_topping_to_pizza('Bufalina','Pomodorini');
call add_topping_to_pizza('Bufalina','Mozzarella di bufala');
call add_prices_to_pizza('Bufalina', 6, 6.50, 12);
call add_topping_to_pizza('Calamari','Pomodoro');
call add_topping_to_pizza('Calamari','Mozzarella');
call add_topping_to_pizza('Calamari','Calamari');
call add_prices_to_pizza('Calamari', 5.50, 7, 13);
call add_topping_to_pizza('Calamari e gamberetti','Pomodoro');
call add_topping_to_pizza('Calamari e gamberetti','Mozzarella');
call add_topping_to_pizza('Calamari e gamberetti','Calamari');
call add_topping_to_pizza('Calamari e gamberetti','gamberetti');
call add_prices_to_pizza('Calamari e gamberetti', 6, 7.50, 14);
call add_topping_to_pizza('Capricciosa','Pomodoro');
call add_topping_to_pizza('Capricciosa','Mozzarella');
call add_topping_to_pizza('Capricciosa','Carciofini');
call add_topping_to_pizza('Capricciosa','Proisciutto cotto');
call add_topping_to_pizza('Capricciosa','Funghi');
call add_prices_to_pizza('Capricciosa', 5.50, 7, 13);
call add_topping_to_pizza('Carbonara','Mozzarella');
call add_topping_to_pizza('Carbonara','Pancetta');
call add_topping_to_pizza('Carbonara','Panna');
call add_topping_to_pizza('Carbonara','Uovo');
call add_prices_to_pizza('Carbonara', 5.50, 7, 13);
call add_topping_to_pizza('Casereccia','Pomodoro');
call add_topping_to_pizza('Casereccia','Mozzarella');
call add_topping_to_pizza('Casereccia','Patatine');
call add_topping_to_pizza('Casereccia','Salsiccia');
call add_prices_to_pizza('Casereccia', 5.50, 7, 13);
call add_topping_to_pizza('Chiara','Mozzarella');
call add_topping_to_pizza('Chiara','Pomodorini');
call add_topping_to_pizza('Chiara','Gorgonzola');
call add_topping_to_pizza('Chiara','Radicchio');
call add_prices_to_pizza('Chiara', 6.50, 8, 15.00);
call add_topping_to_pizza('Cima','Mozzarella');
call add_topping_to_pizza('Cima','Cime di rapa');
call add_topping_to_pizza('Cima','Salsiccia');
call add_prices_to_pizza('Cima', 5.50, 7, 13);
call add_topping_to_pizza('Cinzia','Pomodoro');
call add_topping_to_pizza('Cinzia','Mozzarella');
call add_topping_to_pizza('Cinzia','Acciughe');
call add_topping_to_pizza('Cinzia','Pomodorini a freddo');
call add_topping_to_pizza('Cinzia','Rucola');
call add_topping_to_pizza('Cinzia','Grana');
call add_prices_to_pizza('Cinzia', 5.50, 7, 13);
call add_topping_to_pizza('Claudio','Pomodoro');
call add_topping_to_pizza('Claudio','Mozzarella');
call add_topping_to_pizza('Claudio','Prosciutto cotto');
call add_topping_to_pizza('Claudio','Salame piccante');
call add_topping_to_pizza('Claudio','Olive verdi piccanti');
call add_topping_to_pizza('Claudio','Patatine');
call add_topping_to_pizza('Claudio','Taleggio');
call add_prices_to_pizza('Claudio', 6.50, 8, 15);
call add_topping_to_pizza('Contadina','Pomodoro');
call add_topping_to_pizza('Contadina','Mozzarella');
call add_topping_to_pizza('Contadina','Verdure stufate');
call add_topping_to_pizza('Contadina','Salsiccia');
call add_topping_to_pizza('Contadina','Pecorino');
call add_prices_to_pizza('Contadina', 6.50, 8, 15);
call add_topping_to_pizza('Cristian','Pomodoro');
call add_topping_to_pizza('Cristian','Mozzarella');
call add_topping_to_pizza('Cristian','Olive taggiasche');
call add_topping_to_pizza('Cristian','Porcini');
call add_topping_to_pizza('Cristian','Salsiccia');
call add_prices_to_pizza('Cristian', 6.50, 8, 12);
call add_topping_to_pizza('Curiosa','Mozzarella');
call add_topping_to_pizza('Curiosa','Prosciutto cotto');
call add_topping_to_pizza('Curiosa','Panna');
call add_prices_to_pizza('Curiosa', 5.50, 7, 13);
call add_topping_to_pizza('Dadà','Mozzarella');
call add_topping_to_pizza('Dadà','Prosciutto Crudo');
call add_topping_to_pizza('Dadà','Rucola');
call add_topping_to_pizza('Dadà','Scaglie di grana');
call add_prices_to_pizza('Dadà', 6, 7.50, 14);
call add_topping_to_pizza('Damiano','Mozzarella');
call add_topping_to_pizza('Damiano','prosciutto');
call add_topping_to_pizza('Damiano','Panna');
call add_topping_to_pizza('Damiano','Mais');
call add_prices_to_pizza('Damiano', 5.50, 7, 13);
call add_topping_to_pizza('Daniele','Mozzarella');
call add_topping_to_pizza('Daniele','Fontal');
call add_topping_to_pizza('Daniele','Toma');
call add_topping_to_pizza('Daniele','Gorgonzola');
call add_topping_to_pizza('Daniele','Pere');
call add_topping_to_pizza('Daniele','Speck');
call add_prices_to_pizza('Daniele', 6.50, 8, 15);
call add_topping_to_pizza('Delicata','Pomodorini');
call add_topping_to_pizza('Delicata','Stracchino');
call add_topping_to_pizza('Delicata','Rucola');
call add_prices_to_pizza('Delicata', 5.50, 7, 13);
call add_topping_to_pizza('Deliziosa','Pomodoro');
call add_topping_to_pizza('Deliziosa','Mozzarella');
call add_topping_to_pizza('Deliziosa','Tonno');
call add_topping_to_pizza('Deliziosa','Carciofi');
call add_topping_to_pizza('Deliziosa','Olive nere');
call add_prices_to_pizza('Deliziosa', 5.50, 7, 13);
call add_topping_to_pizza('Diavola','Pomodoro');
call add_topping_to_pizza('Diavola','Mozzarella');
call add_topping_to_pizza('Diavola','Salame piccante');
call add_prices_to_pizza('Diavola', 4.50, 6, 11);
call add_topping_to_pizza('Ecio','Pomodoro');
call add_topping_to_pizza('Ecio','Mozzarella');
call add_topping_to_pizza('Ecio','Peperoni fritti');
call add_topping_to_pizza('Ecio','Salsiccia');
call add_topping_to_pizza('Ecio','Grana a freddo');
call add_prices_to_pizza('Ecio', 5.50, 7, 13);
call add_topping_to_pizza('Elisa','Pomodorini');
call add_topping_to_pizza('Elisa','Mozzarella');
call add_topping_to_pizza('Elisa','Olive taggiasche');
call add_topping_to_pizza('Elisa','Rucola');
call add_prices_to_pizza('Elisa', 5.50, 7, 13);
call add_topping_to_pizza('Fabio','Pomodoro');
call add_topping_to_pizza('Fabio','Mozzarella');
call add_topping_to_pizza('Fabio','Guanciale');
call add_topping_to_pizza('Fabio','Olive verdi piccanti');
call add_topping_to_pizza('Fabio','Patatine');
call add_prices_to_pizza('Fabio', 5.50, 7, 13);
call add_topping_to_pizza('Fabione','Doppio impasto');
call add_topping_to_pizza('Fabione','Pomodoro');
call add_topping_to_pizza('Fabione','Salciccia');
call add_topping_to_pizza('Fabione','Noci');
call add_topping_to_pizza('Fabione','Prosciutto cotto');
call add_topping_to_pizza('Fabione','Mozzarella');
call add_topping_to_pizza('Fabione','Patate');
call add_topping_to_pizza('Fabione','Grana');
call add_prices_to_pizza('Fabione', 8.5, 10, 19);
call add_topping_to_pizza('Fabrizio','Mozzarella');
call add_topping_to_pizza('Fabrizio','Pomodorini');
call add_topping_to_pizza('Fabrizio','Olive verdi');
call add_topping_to_pizza('Fabrizio','Lardo');
call add_topping_to_pizza('Fabrizio','Patatine');
call add_topping_to_pizza('Fabrizio','Grana');
call add_topping_to_pizza('Fabrizio','Rucola');
call add_prices_to_pizza('Fabrizio', 7.5, 9, 17);
call add_topping_to_pizza('Fantasia','Pomodoro');
call add_topping_to_pizza('Fantasia','Olive');
call add_topping_to_pizza('Fantasia','Capperi');
call add_topping_to_pizza('Fantasia','Salsiccia');
call add_topping_to_pizza('Fantasia','Mozzarella di bufala a freddo');
call add_prices_to_pizza('Fantasia', 6, 7.5, 14);
call add_topping_to_pizza('Federica','Pomodoro');
call add_topping_to_pizza('Federica','Mozzarella');
call add_topping_to_pizza('Federica','Salciccia');
call add_topping_to_pizza('Federica','Peperoni');
call add_topping_to_pizza('Federica','Radicchio');
call add_topping_to_pizza('Federica','Grana');
call add_prices_to_pizza('Federica', 7, 8.5, 16);
call add_topping_to_pizza('Federico','Pomodoro');
call add_topping_to_pizza('Federico','Olive verdi piccanti');
call add_topping_to_pizza('Federico','Mozzarella di bufala a freddo');
call add_prices_to_pizza('Federico', 5, 6.5, 12);
call add_topping_to_pizza('Francesco','Mozzarella');
call add_topping_to_pizza('Francesco','Pancetta');
call add_topping_to_pizza('Francesco','Patatine');
call add_topping_to_pizza('Francesco','Olive verdi');
call add_topping_to_pizza('Francesco','Grana');
call add_prices_to_pizza('Francesco', 6, 7.5, 14);
call add_topping_to_pizza('Franco','Pomodoro');
call add_topping_to_pizza('Franco','Mozzarella');
call add_topping_to_pizza('Franco','Salame piccante');
call add_topping_to_pizza('Franco','Olive verdi piccanti');
call add_topping_to_pizza('Franco','Peperoni');
call add_topping_to_pizza('Franco','Cipolle');
call add_prices_to_pizza('Franco', 7, 8.5, 16);
call add_topping_to_pizza('Frutti di mare','Pomodoro');
call add_topping_to_pizza('Frutti di mare','Mozzarella');
call add_topping_to_pizza('Frutti di mare','Frutti di mare');
call add_prices_to_pizza('Frutti di mare', 5.50, 7, 13);
call add_topping_to_pizza('Gabry','Pomodorini');
call add_topping_to_pizza('Gabry','Olive taggiasche');
call add_topping_to_pizza('Gabry','Mozzarella di bufala affumicata');
call add_prices_to_pizza('Gabry', 7, 8.5, 16);
call add_topping_to_pizza('Galli','Pomodorini');
call add_topping_to_pizza('Galli','Acciughe');
call add_topping_to_pizza('Galli','Mozzarella di bufala affumicata');
call add_topping_to_pizza('Galli','Rucola');
call add_topping_to_pizza('Galli','Grana');
call add_prices_to_pizza('Galli', 7, 8.6, 16);
call add_topping_to_pizza('Genovese','Pomodorini');
call add_topping_to_pizza('Genovese','Stracchino');
call add_topping_to_pizza('Genovese','Pesto');
call add_topping_to_pizza('Genovese','Grana');
call add_prices_to_pizza('Genovese', 5.50, 7, 13);
call add_topping_to_pizza('Gianotti','Pomodoro');
call add_topping_to_pizza('Gianotti','Mozzarella di bufala');
call add_topping_to_pizza('Gianotti','Porcini');
call add_topping_to_pizza('Gianotti','Salame piccante');
call add_topping_to_pizza('Gianotti','Olive verdi piccanti');
call add_prices_to_pizza('Gianotti', 7, 8.5, 16);
call add_topping_to_pizza('Gilberto','Pomodoro');
call add_topping_to_pizza('Gilberto','Mozzarella');
call add_topping_to_pizza('Gilberto','Aglio');
call add_topping_to_pizza('Gilberto','Acciughe');
call add_topping_to_pizza('Gilberto','Verdure grigliate');
call add_prices_to_pizza('Gilberto', 7, 8.5, 16);
call add_topping_to_pizza('Giuseppe','Pomodoro');
call add_topping_to_pizza('Giuseppe','Mozzarella');
call add_topping_to_pizza('Giuseppe','Prosciutto cotto');
call add_topping_to_pizza('Giuseppe','Fontina');
call add_topping_to_pizza('Giuseppe','Salame piccante');
call add_topping_to_pizza('Giuseppe','Cipolle');
call add_topping_to_pizza('Giuseppe','Olive verdi piccanti');
call add_prices_to_pizza('Giuseppe', 6.5, 8, 15);
call add_topping_to_pizza('Golosa','Pomodoro');
call add_topping_to_pizza('Golosa','Scamorza affumicata');
call add_topping_to_pizza('Golosa','Salsiccia');
call add_topping_to_pizza('Golosa','Patatine');
call add_prices_to_pizza('Golosa', 6, 7.5, 14);
call add_topping_to_pizza('Greca','Pomodoro');
call add_topping_to_pizza('Greca','Mozzarella');
call add_topping_to_pizza('Greca','Olive');
call add_prices_to_pizza('Greca', 4.5, 6, 11);
call add_topping_to_pizza('Gustosa','Mozzarella');
call add_topping_to_pizza('Gustosa','Pomodorini');
call add_topping_to_pizza('Gustosa','Lardo');
call add_topping_to_pizza('Gustosa','Scaglie di grana');
call add_topping_to_pizza('Gustosa','Rucola');
call add_prices_to_pizza('Gustosa', 6, 7.5, 14);
call add_topping_to_pizza('Inferno','Pomodoro');
call add_topping_to_pizza('Inferno','Mozzarella');
call add_topping_to_pizza('Inferno','Salame piccante');
call add_topping_to_pizza('Inferno','Olive verdi piccanti,Tomini');
call add_topping_to_pizza('Inferno','Salsa inferno');
call add_prices_to_pizza('Inferno', 6.5, 8, 15);
call add_topping_to_pizza('Ivan','Pomodoro');
call add_topping_to_pizza('Ivan','Mozzarella');
call add_topping_to_pizza('Ivan','Olive taggiasche');
call add_topping_to_pizza('Ivan','Gorgonzola');
call add_topping_to_pizza('Ivan','Soppressata');
call add_prices_to_pizza('Ivan', 6, 7.5, 15);
call add_topping_to_pizza('Jhonny','Pomodoro');
call add_topping_to_pizza('Jhonny','Mozzarella');
call add_topping_to_pizza('Jhonny','Salame milano');
call add_topping_to_pizza('Jhonny','Taleggio');
call add_prices_to_pizza('Jhonny', 5.50, 7, 13);
call add_topping_to_pizza('Jody','Pomodoro');
call add_topping_to_pizza('Jody','Mozzarella fiordilatte');
call add_topping_to_pizza('Jody','Basilico');
call add_topping_to_pizza('Jody','Mocetta a freddo');
call add_topping_to_pizza('Jody','Rucola');
call add_prices_to_pizza('Jody', 6.5, 8, 15);
call add_topping_to_pizza('Lilla','Pomodoro');
call add_topping_to_pizza('Lilla','Mozzarella');
call add_topping_to_pizza('Lilla','Verdure grigliate');
call add_topping_to_pizza('Lilla','Salsiccia');
call add_topping_to_pizza('Lilla','Philadelphia');
call add_topping_to_pizza('Lilla','Rucola');
call add_prices_to_pizza('Lilla', 7.5, 9, 17);
call add_topping_to_pizza('Livio','Pomodorini');
call add_topping_to_pizza('Livio','Olive verdi');
call add_topping_to_pizza('Livio','Taleggio');
call add_topping_to_pizza('Livio','Salame milano');
call add_topping_to_pizza('Livio','Mozzarella di bufala');
call add_prices_to_pizza('Livio', 6.5, 8, 15);
call add_topping_to_pizza('Lorenzo','Mozzarella');
call add_topping_to_pizza('Lorenzo','Gorgonzola');
call add_topping_to_pizza('Lorenzo','Noci');
call add_topping_to_pizza('Lorenzo','Radicchio');
call add_topping_to_pizza('Lorenzo','Pomodorini');
call add_prices_to_pizza('Lorenzo', 6.5, 8, 15);
call add_topping_to_pizza('Lory 2','Mozzarella');
call add_topping_to_pizza('Lory 2','Gorgonzola');
call add_topping_to_pizza('Lory 2','Noci');
call add_topping_to_pizza('Lory 2','Olive nere');
call add_topping_to_pizza('Lory 2','Salsina piccante');
call add_topping_to_pizza('Lory 2','Rucola');
call add_prices_to_pizza('Lory 2', 6, 7.5, 14);
call add_topping_to_pizza('Lory 3','Pomodoro');
call add_topping_to_pizza('Lory 3','Mozzarella');
call add_topping_to_pizza('Lory 3','Pesto');
call add_topping_to_pizza('Lory 3','Olive taggiasche');
call add_topping_to_pizza('Lory 3','Basilico');
call add_prices_to_pizza('Lory 3', 6, 8, 15);
call add_topping_to_pizza('Luca','Pomodoro');
call add_topping_to_pizza('Luca','Mozzarella');
call add_topping_to_pizza('Luca','Salame milano');
call add_topping_to_pizza('Luca','Olive nere');
call add_topping_to_pizza('Luca','Patatine');
call add_prices_to_pizza('Luca', 5.5, 7, 13);
call add_topping_to_pizza('Luciano','Pomodoro');
call add_topping_to_pizza('Luciano','Mozzarella');
call add_topping_to_pizza('Luciano','Soppressata');
call add_prices_to_pizza('Luciano', 4.5, 6, 11);
call add_topping_to_pizza('Ludos','Pomodorini');
call add_topping_to_pizza('Ludos','Stracchino');
call add_topping_to_pizza('Ludos','Tonno');
call add_prices_to_pizza('Ludos', 6.5, 8, 15);
call add_topping_to_pizza('Magister','Pomodoro');
call add_topping_to_pizza('Magister','Mozzarella');
call add_topping_to_pizza('Magister','Salame milano');
call add_topping_to_pizza('Magister','Cima');
call add_topping_to_pizza('Magister','Peperoni');
call add_topping_to_pizza('Magister','Pecorino');
call add_prices_to_pizza('Magister', 7, 8.5, 16);
call add_topping_to_pizza('Margherita','Pomodoro');
call add_topping_to_pizza('Margherita','Mozzarella');
call add_prices_to_pizza('Margherita', 4, 5, 9);
call add_topping_to_pizza('Mari e monti','Pomodoro');
call add_topping_to_pizza('Mari e monti','Mozzarella');
call add_topping_to_pizza('Mari e monti','Frutti di mare');
call add_topping_to_pizza('Mari e monti','Funghi');
call add_prices_to_pizza('Mari e monti', 6, 7.5, 14);
call add_topping_to_pizza('Marinara','Pomodoro');
call add_topping_to_pizza('Marinara','Aglio');
call add_prices_to_pizza('Marinara', 4, 5, 9);
call add_topping_to_pizza('Massimo','Pesto');
call add_topping_to_pizza('Massimo','Pomodorini');
call add_topping_to_pizza('Massimo','Capperi');
call add_topping_to_pizza('Massimo','Stracchino');
call add_topping_to_pizza('Massimo','Rucola');
call add_prices_to_pizza('Massimo', 6.5, 8, 15);
call add_topping_to_pizza('Mattia','Pancetta');
call add_topping_to_pizza('Mattia','Cipolle');
call add_topping_to_pizza('Mattia','Melanzane fritte');
call add_topping_to_pizza('Mattia','Mozzarella di bufala a freddo');
call add_prices_to_pizza('Mattia', 7.5, 9, 17);
call add_topping_to_pizza('Modesta','Pomodoro');
call add_topping_to_pizza('Modesta','Mozzarella di bufala');
call add_topping_to_pizza('Modesta','Salsiccia');
call add_prices_to_pizza('Modesta', 5.5, 7, 13);
call add_topping_to_pizza('Napoli','Pomodoro');
call add_topping_to_pizza('Napoli','Mozzarella');
call add_topping_to_pizza('Napoli','Acciughe');
call add_prices_to_pizza('Napoli', 4.5, 6, 11);
call add_topping_to_pizza('Natasha','Pomodoro');
call add_topping_to_pizza('Natasha','Mozzarella');
call add_topping_to_pizza('Natasha','Bresaola');
call add_topping_to_pizza('Natasha','Rucola');
call add_topping_to_pizza('Natasha','Burrata a freddo');
call add_prices_to_pizza('Natasha', 6.5, 8, 15);
call add_topping_to_pizza('N''duja','Pomodoro');
call add_topping_to_pizza('N''duja','Mozzarella');
call add_topping_to_pizza('N''duja','N''duja');
call add_prices_to_pizza('N''duja', 4.5, 6, 11);
call add_topping_to_pizza('Neurolaser','Pomodorini');
call add_topping_to_pizza('Neurolaser','Olive nere');
call add_topping_to_pizza('Neurolaser','Pancetta affumicata');
call add_topping_to_pizza('Neurolaser','Mozzarella di bufala');
call add_prices_to_pizza('Neurolaser', 6.5, 8, 15);
call add_topping_to_pizza('Nicolò','Mozzarella');
call add_topping_to_pizza('Nicolò','Prosciutto cotto');
call add_topping_to_pizza('Nicolò','Wurstel');
call add_topping_to_pizza('Nicolò','Scamorza');
call add_prices_to_pizza('Nicolò', 5.5, 7, 13);
call add_topping_to_pizza('Novità','Mozzarella');
call add_topping_to_pizza('Novità','Gorgonzola');
call add_topping_to_pizza('Novità','Noci');
call add_topping_to_pizza('Novità','Pere');
call add_prices_to_pizza('Novità', 5.5, 7, 13);
call add_topping_to_pizza('Obi','Pomodoro');
call add_topping_to_pizza('Obi','Mozzarella');
call add_topping_to_pizza('Obi','Zucchine');
call add_topping_to_pizza('Obi','Wurstel');
call add_topping_to_pizza('Obi','Funghi');
call add_topping_to_pizza('Obi','Grana');
call add_prices_to_pizza('Obi', 6.5, 8, 15);
call add_topping_to_pizza('Omar','Mozzarella');
call add_topping_to_pizza('Omar','Funghi');
call add_topping_to_pizza('Omar','Patatine');
call add_topping_to_pizza('Omar','Wurstel');
call add_topping_to_pizza('Omar','Panna');
call add_prices_to_pizza('Omar', 6, 7.5, 14);
call add_topping_to_pizza('Origanata','Pomodoro');
call add_topping_to_pizza('Origanata','Cipolle');
call add_topping_to_pizza('Origanata','Acciughe');
call add_topping_to_pizza('Origanata','Olive nere');
call add_topping_to_pizza('Origanata','Pecorino');
call add_prices_to_pizza('Origanata', 5.5, 7, 13);
call add_topping_to_pizza('Ornella','Pomodoro');
call add_topping_to_pizza('Ornella','Mozzarella');
call add_topping_to_pizza('Ornella','Gorgonzola');
call add_topping_to_pizza('Ornella','Tonno');
call add_topping_to_pizza('Ornella','Olive verdi piccanti');
call add_prices_to_pizza('Ornella', 6, 7.5, 14);
call add_topping_to_pizza('Ortolana','Pomodoro');
call add_topping_to_pizza('Ortolana','Mozzarella');
call add_topping_to_pizza('Ortolana','Verdure stufate');
call add_prices_to_pizza('Ortolana', 5.5, 7, 13);
call add_topping_to_pizza('Parigina','Pomodoro');
call add_topping_to_pizza('Parigina','Mozzarella');
call add_topping_to_pizza('Parigina','Panna');
call add_topping_to_pizza('Parigina','Prosciutto crudo');
call add_prices_to_pizza('Parigina', 6, 7.5, 14);
call add_topping_to_pizza('Parmigiana','Pomodoro');
call add_topping_to_pizza('Parmigiana','Mozzarella');
call add_topping_to_pizza('Parmigiana','Prosciutto cotto');
call add_topping_to_pizza('Parmigiana','Melanzane fritte');
call add_topping_to_pizza('Parmigiana','Parmigiano');
call add_prices_to_pizza('Parmigiana', 6, 7.5, 14);
call add_topping_to_pizza('Pasticciata','Pomodoro');
call add_topping_to_pizza('Pasticciata','Mozzarella');
call add_topping_to_pizza('Pasticciata','Salsiccia');
call add_topping_to_pizza('Pasticciata','Friarielli');
call add_topping_to_pizza('Pasticciata','Olive verdi');
call add_topping_to_pizza('Pasticciata','Salamino');
call add_prices_to_pizza('Pasticciata', 7.5, 9, 17);
call add_topping_to_pizza('Patatosa','Mozzarella');
call add_topping_to_pizza('Patatosa','Taleggio');
call add_topping_to_pizza('Patatosa','Patatine');
call add_topping_to_pizza('Patatosa','Rosmarino');
call add_prices_to_pizza('Patatosa', 5.5, 7, 13);
call add_topping_to_pizza('Patty','Pomodoro');
call add_topping_to_pizza('Patty','Mozzarella');
call add_topping_to_pizza('Patty','Peperoni');
call add_topping_to_pizza('Patty','Gorgonzola');
call add_topping_to_pizza('Patty','Acciughe');
call add_topping_to_pizza('Patty','Cipolla');
call add_prices_to_pizza('Patty', 6.5, 8, 15);
call add_topping_to_pizza('Philadelphia','Pomodoro');
call add_topping_to_pizza('Philadelphia','Mozzarella');
call add_topping_to_pizza('Philadelphia','Philadelphia');
call add_topping_to_pizza('Philadelphia','Rucola');
call add_prices_to_pizza('Philadelphia', 5, 6.5, 12);
call add_topping_to_pizza('Pizza in','Pomodoro');
call add_topping_to_pizza('Pizza in','Mozzarella');
call add_topping_to_pizza('Pizza in','Salsiccia');
call add_topping_to_pizza('Pizza in','Olive');
call add_topping_to_pizza('Pizza in','Capperi');
call add_topping_to_pizza('Pizza in','Peperoncino');
call add_prices_to_pizza('Pizza in', 5.5, 7, 13);
call add_topping_to_pizza('Porcini','Pomodoro');
call add_topping_to_pizza('Porcini','Mozzarella');
call add_topping_to_pizza('Porcini','Funghi porcini');
call add_prices_to_pizza('Porcini', 5.5, 7, 13);
call add_topping_to_pizza('Primavera','Pomodorini');
call add_topping_to_pizza('Primavera','Rucola');
call add_topping_to_pizza('Primavera','Grana');
call add_prices_to_pizza('Primavera', 4.5, 6, 15);
call add_topping_to_pizza('Principessa','Pomodorini');
call add_topping_to_pizza('Principessa','Mozzarella');
call add_topping_to_pizza('Principessa','Zucchini');
call add_topping_to_pizza('Principessa','Gamberetti');
call add_topping_to_pizza('Principessa','Rucola');
call add_prices_to_pizza('Principessa', 6.5, 8, 15);
call add_topping_to_pizza('Prosciutto','Pomodoro');
call add_topping_to_pizza('Prosciutto','Mozzarella');
call add_topping_to_pizza('Prosciutto','Prosciutto cotto');
call add_prices_to_pizza('Prosciutto', 4.5, 6, 11);
call add_topping_to_pizza('Prosciutto e funghi','Pomodoro');
call add_topping_to_pizza('Prosciutto e funghi','Mozzarella');
call add_topping_to_pizza('Prosciutto e funghi','Prosciutto cotto');
call add_topping_to_pizza('Prosciutto e funghi','Funghi');
call add_prices_to_pizza('Prosciutto e funghi', 5, 6.5, 12);
call add_topping_to_pizza('Pugliese','Pomodoro');
call add_topping_to_pizza('Pugliese','Mozzarella');
call add_topping_to_pizza('Pugliese','Cipolla');
call add_prices_to_pizza('Pugliese', 4.5, 6, 11);
call add_topping_to_pizza('Reale','Pomodoro');
call add_topping_to_pizza('Reale','Mozzarella');
call add_topping_to_pizza('Reale','Salame affumicato');
call add_topping_to_pizza('Reale','Philadelphia');
call add_topping_to_pizza('Reale','Rucola');
call add_prices_to_pizza('Reale', 5.5, 7, 13);
call add_topping_to_pizza('Regina','Mozzarella');
call add_topping_to_pizza('Regina','Fontina');
call add_topping_to_pizza('Regina','Prosciutto cotto');
call add_topping_to_pizza('Regina','Funghi porcini');
call add_prices_to_pizza('Regina', 6.5, 8, 15);
call add_topping_to_pizza('Ricottella','Pomodoro');
call add_topping_to_pizza('Ricottella','Mozzarella');
call add_topping_to_pizza('Ricottella','Ricotta');
call add_topping_to_pizza('Ricottella','Rucola');
call add_prices_to_pizza('Ricottella', 5.5, 7, 13);
call add_topping_to_pizza('Rosanna','Pomodoro');
call add_topping_to_pizza('Rosanna','Aglio');
call add_topping_to_pizza('Rosanna','Mozzarella fiordilatte a freddo');
call add_topping_to_pizza('Rosanna','Basilico');
call add_topping_to_pizza('Rosanna','Acciughe');
call add_prices_to_pizza('Rosanna', 5.5, 7, 13);
call add_topping_to_pizza('Rustica','Mozzarella');
call add_topping_to_pizza('Rustica','Scamorza');
call add_topping_to_pizza('Rustica','Pancetta');
call add_prices_to_pizza('Rustica', 5, 6.5, 12);
call add_topping_to_pizza('Salmone','Pomodoro');
call add_topping_to_pizza('Salmone','Mozzarella');
call add_topping_to_pizza('Salmone','Panna');
call add_topping_to_pizza('Salmone','Salmone');
call add_prices_to_pizza('Salmone', 5, 6.5, 12);
call add_topping_to_pizza('Saporita','Mozzarella');
call add_topping_to_pizza('Saporita','Bresaola');
call add_topping_to_pizza('Saporita','Rucola');
call add_topping_to_pizza('Saporita','Parmigiano');
call add_prices_to_pizza('Saporita', 6, 7.5, 14);
call add_topping_to_pizza('Scarola','Pomodoro');
call add_topping_to_pizza('Scarola','Mozzarella');
call add_topping_to_pizza('Scarola','Scarola');
call add_topping_to_pizza('Scarola','Acciughe');
call add_topping_to_pizza('Scarola','Capperi');
call add_topping_to_pizza('Scarola','Olive Taggiasche');
call add_prices_to_pizza('Scarola', 6.5, 8, 15);
call add_topping_to_pizza('Settimo','Pomodoro');
call add_topping_to_pizza('Settimo','Mozzarella');
call add_topping_to_pizza('Settimo','Porcini');
call add_topping_to_pizza('Settimo','Scamorza affumicata');
call add_topping_to_pizza('Settimo','Speck');
call add_prices_to_pizza('Settimo', 6.5, 8, 15);
call add_topping_to_pizza('Sfiziosa','Pomodorini');
call add_topping_to_pizza('Sfiziosa','Mozzarella di bufala');
call add_topping_to_pizza('Sfiziosa','Salsiccia');
call add_topping_to_pizza('Sfiziosa','Rucola');
call add_prices_to_pizza('Sfiziosa', 6.5, 8, 15);
call add_topping_to_pizza('Siciliana','Pomodoro');
call add_topping_to_pizza('Siciliana','Mozzarella');
call add_topping_to_pizza('Siciliana','Acciughe');
call add_topping_to_pizza('Siciliana','Capperi');
call add_topping_to_pizza('Siciliana','Olive');
call add_prices_to_pizza('Siciliana', 5.5, 7, 13);
call add_topping_to_pizza('Simone','Pomodoro');
call add_topping_to_pizza('Simone','Mozzarella');
call add_topping_to_pizza('Simone','Frutti di mare');
call add_topping_to_pizza('Simone','Salmone affumicato');
call add_topping_to_pizza('Simone','Prosciutto');
call add_prices_to_pizza('Simone', 6.5, 8, 15);
call add_topping_to_pizza('Speciale','Pomodoro');
call add_topping_to_pizza('Speciale','Mozzarella');
call add_topping_to_pizza('Speciale','Gamberetti');
call add_topping_to_pizza('Speciale','Rucola');
call add_prices_to_pizza('Speciale', 5.5, 7, 13);
call add_topping_to_pizza('Stefano','Pomodoro');
call add_topping_to_pizza('Stefano','Mozzarella');
call add_topping_to_pizza('Stefano','Verdura');
call add_topping_to_pizza('Stefano','Salsiccia');
call add_topping_to_pizza('Stefano','Bufala');
call add_prices_to_pizza('Stefano', 6.5, 8, 15);
call add_topping_to_pizza('Strana','Pomodoro');
call add_topping_to_pizza('Strana','Mozzarella');
call add_topping_to_pizza('Strana','Salsiccia');
call add_topping_to_pizza('Strana','Pomodorini a freddo');
call add_topping_to_pizza('Strana','Rucola');
call add_topping_to_pizza('Strana','Grana');
call add_prices_to_pizza('Strana', 6.5, 8, 15);
call add_topping_to_pizza('Tartufo','Mozzarella');
call add_topping_to_pizza('Tartufo','Crema di tartufo');
call add_topping_to_pizza('Tartufo','Funghi');
call add_topping_to_pizza('Tartufo','Panna');
call add_topping_to_pizza('Tartufo','Speck');
call add_prices_to_pizza('Tartufo', 6.5, 8, 15);
call add_topping_to_pizza('Tentatore','Pomodorini');
call add_topping_to_pizza('Tentatore','Cotto');
call add_topping_to_pizza('Tentatore','Mozzarella di bufala');
call add_topping_to_pizza('Tentatore','Rucola');
call add_prices_to_pizza('Tentatore', 6, 7.5, 14);
call add_topping_to_pizza('Tentatrice','Pomodoro');
call add_topping_to_pizza('Tentatrice','Mozzarella');
call add_topping_to_pizza('Tentatrice','Scamorza');
call add_topping_to_pizza('Tentatrice','Salame piccante');
call add_topping_to_pizza('Tentatrice','Prosciutto cotto');
call add_prices_to_pizza('Tentatrice', 6, 7.5, 14);
call add_topping_to_pizza('Teo','Mozzarella');
call add_topping_to_pizza('Teo','Olive');
call add_topping_to_pizza('Teo','Noci');
call add_topping_to_pizza('Teo','Scaglie di grana');
call add_prices_to_pizza('Teo', 5, 6.5, 12);
call add_topping_to_pizza('Toni','Pomodoro');
call add_topping_to_pizza('Toni','Mozzarella');
call add_topping_to_pizza('Toni','Friarielli');
call add_topping_to_pizza('Toni','Gorgonzola');
call add_topping_to_pizza('Toni','N''duja');
call add_prices_to_pizza('Toni', 6, 7.5, 14);
call add_topping_to_pizza('Tonno e cipolle','Pomodoro');
call add_topping_to_pizza('Tonno e cipolle','Mozzarella');
call add_topping_to_pizza('Tonno e cipolle','Tonno');
call add_topping_to_pizza('Tonno e cipolle','Cipolle');
call add_prices_to_pizza('Tonno e cipolle', 5, 6.5, 12);
call add_topping_to_pizza('Tropea','Pomodoro');
call add_topping_to_pizza('Tropea','Mozzarella');
call add_topping_to_pizza('Tropea','Gorgonzola');
call add_topping_to_pizza('Tropea','Salame piccante');
call add_topping_to_pizza('Tropea','Cipolle di Tropea');
call add_prices_to_pizza('Tropea', 5.5, 7, 13);
call add_topping_to_pizza('Valdostana','Fontina');
call add_topping_to_pizza('Valdostana','Cotto');
call add_topping_to_pizza('Valdostana','Mozzarella');
call add_prices_to_pizza('Valdostana', 5.5, 7, 13);
call add_topping_to_pizza('Viennese','Pomodoro');
call add_topping_to_pizza('Viennese','Mozzarella');
call add_topping_to_pizza('Viennese','Speck');
call add_topping_to_pizza('Viennese','Brie');
call add_prices_to_pizza('Viennese', 5.5, 7, 13);
call add_topping_to_pizza('Wurstel','Pomodoro');
call add_topping_to_pizza('Wurstel','Mozzarella');
call add_topping_to_pizza('Wurstel','Wurstel');
call add_prices_to_pizza('Wurstel', 4.5, 6, 11);
